   
TecnotekExpedienteBundle_homepage:
    pattern:  /
    defaults: { _controller: TecnotekExpedienteBundle:Default:index }
    
_expediente_secured:
    resource: "@TecnotekExpedienteBundle/Controller/SecuredController.php"
    type:     annotation

#_expediente:
#    resource: "@TecnotekExpedienteBundle/Controller/DefaultController.php"
#    type:     annotation
#    prefix:   /expediente

_change_admin_password:
    pattern: /sysadmin/administrador/changePassword
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:changeUserPassword }

#Super Administrador
_expediente_sysadmin:
    pattern:  /sysadmin
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:index }
    
_expediente_sysadmin_administrador:
    pattern:  /sysadmin/administrador
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorList }

_delete_admin:
    pattern:  /sysadmin/administrador/delete/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorDelete }

_expediente_sysadmin_admin_create:
    pattern:  /sysadmin/administrador/create
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorCreate }

_expediente_sysadmin_admin_save:
    pattern:  /sysadmin/administrador/save
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorSave }

_expediente_sysadmin_admin_update:
    pattern:  /sysadmin/administrador/update
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorUpdate }

_expediente_sysadmin_admin_show:
    pattern:  /sysadmin/administrador/show/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorShow }

_expediente_sysadmin_admin_show_simple:
    pattern:  /sysadmin/administrador/show
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:administradorShow }

#CRUD de Coordinadores para SysAdmin
_expediente_sysadmin_coordinador:
    pattern:  /sysadmin/coordinador
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorList }

_delete_coordinador:
    pattern:  /sysadmin/coordinador/delete/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorDelete }

_expediente_sysadmin_coordinador_create:
    pattern:  /sysadmin/coordinador/create
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorCreate }

_expediente_sysadmin_coordinador_save:
    pattern:  /sysadmin/coordinador/save
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorSave }

_expediente_sysadmin_coordinador_update:
    pattern:  /sysadmin/coordinador/update
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorUpdate }

_expediente_sysadmin_coordinador_show:
    pattern:  /sysadmin/coordinador/show/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorShow }

_expediente_sysadmin_coordinador_show_simple:
    pattern:  /sysadmin/coordinador/show
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:coordinadorShow }
#Fin de CRUD de Coordinadores para SysAdmin

#CRUD de Profesores para SysAdmin
_expediente_sysadmin_profesor:
    pattern:  /sysadmin/profesor
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorList }

_delete_profesor:
    pattern:  /sysadmin/profesor/delete/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorDelete }

_expediente_sysadmin_profesor_create:
    pattern:  /sysadmin/profesor/create
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorCreate }

_expediente_sysadmin_profesor_save:
    pattern:  /sysadmin/profesor/save
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorSave }

_expediente_sysadmin_profesor_update:
    pattern:  /sysadmin/profesor/update
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorUpdate }

_expediente_sysadmin_profesor_show:
    pattern:  /sysadmin/profesor/show/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorShow }

_expediente_sysadmin_profesor_show_simple:
    pattern:  /sysadmin/profesor/show
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:profesorShow }
#Fin de CRUD de Coordinadores para Profesor

#CRUD de routes para SysAdmin
_expediente_sysadmin_route:
    pattern:  /sysadmin/route
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeList }

_delete_route:
    pattern:  /sysadmin/route/delete/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeDelete }

_expediente_sysadmin_route_create:
    pattern:  /sysadmin/route/create
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeCreate }

_expediente_sysadmin_route_save:
    pattern:  /sysadmin/route/save
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeSave }

_expediente_sysadmin_route_update:
    pattern:  /sysadmin/route/update
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeUpdate }

_expediente_sysadmin_route_show:
    pattern:  /sysadmin/route/show/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeShow }

_expediente_sysadmin_route_show_simple:
    pattern:  /sysadmin/route/show
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:routeShow }
#Fin de CRUD de routes

#CRUD de bus para SysAdmin
_expediente_sysadmin_bus:
    pattern:  /sysadmin/bus
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busList }

_delete_bus:
    pattern:  /sysadmin/bus/delete/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busDelete }

_expediente_sysadmin_bus_create:
    pattern:  /sysadmin/bus/create
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busCreate }

_expediente_sysadmin_bus_save:
    pattern:  /sysadmin/bus/save
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busSave }

_expediente_sysadmin_bus_update:
    pattern:  /sysadmin/bus/update
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busUpdate }

_expediente_sysadmin_bus_show:
    pattern:  /sysadmin/bus/show/{id}
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busShow }

_expediente_sysadmin_bus_show_simple:
    pattern:  /sysadmin/bus/show
    defaults: { _controller: TecnotekExpedienteBundle:SuperAdmin:busShow }
#Fin de CRUD de routes

#Administrador
_expediente_admin:
    pattern:  /admin
    defaults: { _controller: TecnotekExpedienteBundle:Default:index }
    
#Profesor
_expediente_profesor:
    pattern:  /profesor
    defaults: { _controller: TecnotekExpedienteBundle:Default:index }